// <auto-generated />
using System;
using GestaoTarefas2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoTarefas2.Migrations
{
    [DbContext(typeof(GestaoTarefasDbContext))]
    [Migration("20191209130054_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestaoTarefas2.Models.Cargos", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeCargo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CargoId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("GestaoTarefas2.Models.Departamentos", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("GestaoTarefas2.Models.Funcionarios", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<int?>("CargosCargoId")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentosDepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NTelemovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("FuncionarioId");

                    b.HasIndex("CargosCargoId");

                    b.HasIndex("DepartamentosDepartamentoId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("GestaoTarefas2.Models.Tarefas", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionariosFuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeOrdena")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("NomeTarefa")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("TiposTarefasTipoId")
                        .HasColumnType("int");

                    b.HasKey("TarefaId");

                    b.HasIndex("FuncionariosFuncionarioId");

                    b.HasIndex("TiposTarefasTipoId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("GestaoTarefas2.Models.TiposTarefas", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoTarefa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoId");

                    b.ToTable("TiposTarefas");
                });

            modelBuilder.Entity("GestaoTarefas2.Models.Funcionarios", b =>
                {
                    b.HasOne("GestaoTarefas2.Models.Cargos", "Cargos")
                        .WithMany("Funcionarios")
                        .HasForeignKey("CargosCargoId");

                    b.HasOne("GestaoTarefas2.Models.Departamentos", "Departamentos")
                        .WithMany()
                        .HasForeignKey("DepartamentosDepartamentoId");
                });

            modelBuilder.Entity("GestaoTarefas2.Models.Tarefas", b =>
                {
                    b.HasOne("GestaoTarefas2.Models.Funcionarios", "Funcionarios")
                        .WithMany("Tarefas")
                        .HasForeignKey("FuncionariosFuncionarioId");

                    b.HasOne("GestaoTarefas2.Models.TiposTarefas", "TiposTarefas")
                        .WithMany("Tarefas")
                        .HasForeignKey("TiposTarefasTipoId");
                });
#pragma warning restore 612, 618
        }
    }
}
